### ISSUE TITLE
Favicon support

### ISSUE THREAD

**Issue by meyt** [meyt/linkpreview#1]
Other implementations:

- https://github.com/phillipsm/pyfav
- https://github.com/mat/besticon
- https://github.com/antongunov/favicongrabber.com
- https://github.com/curabase/favicon-getter
- https://github.com/scottwernervt/favicon

**Comment by narayanan-ka** [comment]
@meyt Which of the above you recommend using ?

**Comment by meyt** [comment]
@narayanan-ka i've never used them before.

**Comment by narayanan-ka** [comment]
@meyt Is it possible for you to just add an enhancement function to get favicon using the first python package ? It would be a welcome addition to the repo.

**Comment by narayanan-ka** [comment]
Could you please share an example with regards to your code using perhaps the 1st package on how best to do it ?

**Comment by amiantos** [comment]
I'd love to see this functionality in this package. Is there a way I can help? Should I submit a PR if I want?
