### ISSUE TITLE
og:site_name support

### ISSUE THREAD

**Issue by ummjackson** [meyt/linkpreview#14]
Hi there, thanks for building this - it's very handy and works great! I was hoping you might be interested in adding the `og:site_name` variable to fetch the Site Name tag if present? Most big websites include this and it'd be very helpful to have. 

If you'd prefer I go ahead and work on a Pull Request just let me know, but figured as maintainer you're most familiar with how this could quickly be added.

**Comment by meyt** [comment]
Hi @ummjackson, thank you! Good idea i'll implement it very soon.
