### ISSUE TITLE
Add serializer

### ISSUE THREAD

**Issue by narayanan-ka** [meyt/linkpreview#20]
Its a great package @meyt. Thanks. I;m trying to integrate this to my django app and facing issues. If you could help?
https://stackoverflow.com/questions/76818922/typeerror-object-of-type-linkpreview-is-not-json-serializable

**Comment by meyt** [comment]
Thanks @narayanan-ka, Please update to [v0.7.0](https://pypi.org/project/linkpreview/0.7.0/), I've added a [serializer](https://github.com/meyt/linkpreview/commit/0789c521c6881f63ff5e7f90bca7041c7441aa6a) method.

Based on your question, you should use it like this:
```python

...

return Response(link_preview(link).to_dict(), status=status.HTTP_200_OK)

...

```

**Comment by narayanan-ka** [comment]
- Hey @meyt Thanks for helping out, While it was not your obligation to do so since it is outside of the scope of Github , I really appreciate it. This addition is a valuable enhancement to the package for all on the django rest end.  While researching for link preview, I came across this article. Do check it out. a service call peekalink https://lifenautjoe.medium.com/announcing-peekalink-an-api-to-magically-preview-any-link-f89fb666fdb8 . Do let me know what you think ?

**Comment by narayanan-ka** [comment]
Getting "Invalid content type" on this line ---- > content, url = grabber.get_content(url)

Here are the snippets based on your suggestion : 
`
class LinkIsPreviewable(APIView):
    permission_classes = (IsAuthenticated, IsNotSuspended)
    throttle_scope = 'link_preview'

    def post(self, request):
        serializer = LinkPreviewSerializer(data=request.data, context={"request": request})
        data = serializer.validated_data
        link = data.get('link')

        try:
            is_previewable = link_preview(link).to_dict()
        except Exception as e:
            # We dont care whether it succeeded or not
            is_previewable = False
    
        return Response({
            'is_previewable': is_previewable,
        }, status=status.HTTP_200_OK)


class PreviewLink(APIView):
    permission_classes = (IsAuthenticated, IsNotSuspended)
    throttle_scope = 'link_preview'

    def post(self, request):
        serializer = LinkPreviewSerializer(data=request.data, context={"request": request})
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data
        link = data.get('link')

        user = request.user

        link_preview = user.preview_link(link)

        return Response(link_preview, status=status.HTTP_200_OK)
`
`def preview_link(self, link,):
        # if self.language:
        #     return link_preview(url=link)

        # return link_preview(url=link,)
        return link_preview(url=link).to_dict()`

**Comment by narayanan-ka** [comment]
Hi @meyt , Technically it should more likely be working but I'm getting this inside my flutter app : 
![Screenshot_1691151004](https://github.com/meyt/linkpreview/assets/76656328/97ff31cf-c93e-45e6-9236-bfb42a79bdd5)

**Comment by meyt** [comment]
@narayanan-ka services like Peekalink do a lot of stuff to get the preview. things like full browser render is overkill. what is next? generate the preview by using AI?! site owners must take care of right meta tags.

about the twitter (X🤡) and most of websites [use bot user-agents](https://github.com/meyt/linkpreview/issues/9#issuecomment-925643793).

**Comment by narayanan-ka** [comment]
Understood.
