### ISSUE TITLE
ReSize image 

### ISSUE THREAD

**Issue by narayanan-ka** [meyt/linkpreview#22]
It would be great if the package could allow resizing the image into some pre-defined dimensions so that the frontend app could receive it in the said dimensions.

**Comment by meyt** [comment]
Thank you @narayanan-ka, but no, it would not. let this package do its own [simple job well.](https://en.wikipedia.org/wiki/Unix_philosophy#:~:text=The%20Unix%20philosophy%20is%20documented,%2C%20as%20yet%20unknown%2C%20program)
