### ISSUE TITLE
Favicon Bug

### ISSUE THREAD

**Issue by benrapport** [meyt/linkpreview#23]
return tuple(
            map(
                lambda x: tuple(map(int, x.split("x"))),

This code introduced back in October introduces a bug, as many modern favicon sizes are given by the character: ×.

**Comment by meyt** [comment]
@benrapport Based on [W3C](https://www.w3.org/TR/2011/WD-html5-author-20110809/links.html#attr-link-sizes) docs, the character "×" (U+00D7 × MULTIPLICATION SIGN) is invalid.
