### ISSUE TITLE
Fallback when tags aren't available?

### ISSUE THREAD

**Issue by ajkessel** [meyt/linkpreview#26]
Have you considered adding some fallback behavior, for example, when no "description" tag is available? Some preview APIs will pull and format the first paragraph of text as a substitute. Unless I'm missing something, that isn't possible with the current implementation, right? (i.e. you'd have to figure it out manually)

**Comment by meyt** [comment]
@ajkessel This has already been implemented. When there is no meta tag available, linkpreview tries to find the first HTML paragraph tag and use it as the "description". [Example 1](https://github.com/meyt/linkpreview/blob/master/tests/stuff/generic/p-desc.html) [Example 2](https://github.com/meyt/linkpreview/blob/master/tests/stuff/generic/h1-p-desc.html)

If you see anything wrong, please provide an example and describe the behavior you expect.

**Comment by ajkessel** [comment]
Apparently I was testing it on a page without a <p> tag--only list items (essentially a main menu). Could it be tweaked to pull in whatever text there is when <p> isn't found?

**Comment by meyt** [comment]
There must be a reliable definition to identify a description. Anything else makes it slower to guess and process, and the result would be meaningless. For example, you might see description results like: "About", "Download", "Manage Cookies", "Email", "2024", "📙", "Table of contents", etc.

Anyway, you can tweak it like this to suit your needs:

```python
import requests

from linkpreview.preview import Generic
from linkpreview import LinkPreview, Link


class MyGeneric(Generic):

    @property
    def description(self):
        r = super().description
        if r:
            return r

        thetag = self._soup.find("div")
        if thetag and thetag.string:
            return thetag.string


url = "https://google.com"
content = requests.get(url).text
parser = "html.parser"

link = Link(url, content)
lp = LinkPreview(link, parser)
lp.generic = MyGeneric(lp.link, parser)
lp.sources = (lp.opengraph, lp.twitter, lp.microdata, lp.jsonld, lp.generic)

print(lp.description)
```

**Comment by ajkessel** [comment]
Thanks! I'll play around with that example.
