### ISSUE TITLE
Add LinkGrabber constructor parameters to link_preview shortcut function

### ISSUE THREAD

**Issue by Chadys** [meyt/linkpreview#27]
Hello, I am using your library and find it very practical! Currently using it to add an url preview block to some of my wagtail apps.

Only issue I have is that when I want to change some parameters of `LinkGrabber` from their default ones (`maxsize` for example), I need to write something similar to what `link_preview()` is already doing only to add those parameters.
Couldn't we add some `**kwargs` to `link_preview` and directly pass those to `LinkGrabber()`? Or is there a reason not to?

**Comment by meyt** [comment]
Thanks @Chadys, [v0.10](https://pypi.org/project/linkpreview/0.10.0/) released, [now](https://github.com/meyt/linkpreview/commit/0c81552c6d20d8f1bd32274f1d9c43fd4bb525a4) you can use those parameters:

```python
from linkpreview import link_preview

preview = link_preview(
    "http://github.com/",
    headers="chrome",
    initial_timeout=5,
    receive_timeout=3,
    maxsize=1048576,
    chunk_size=10,
)
print("title:", preview.title)
```
