### ISSUE TITLE
Shortened Youtube Urls not supported

### ISSUE THREAD

**Issue by hendrikschneider** [meyt/linkpreview#28]
Hello,

when a youtube url is shortened like this, it takes a long time and does return proper data.

URL: https://youtu.be/RiohwnNs5as

This kind of url seems to be available when trying to share a newer youtube video.

Best wishes

**Comment by meyt** [comment]
Hi @hendrikschneider,
Please try a [different user-agent](https://github.com/meyt/linkpreview?tab=readme-ov-file#advanced).

for example it works with ios messages user-agent.
```python
from linkpreview import link_preview
url = "https://youtu.be/RiohwnNs5as"
preview = link_preview(url, headers='imessagebot')
print("title:", preview.title)
print("description:", preview.description)
```

**Comment by hendrikschneider** [comment]
Hey @meyt Thank you for your quick response. This seems to work properly, thank you a lot!

I am using the normal parser and for me the data parsing takes a long time with these links. Do you experience the same?

**Comment by meyt** [comment]
You're welcome, 
No the parser is fine. here is the timing for this case:
```
html.parser:  0.09210538864135742
lxml:         0.07886672019958496
```

**Comment by hendrikschneider** [comment]
Hey @meyt Thank you for the check! I will check this one my side!

Best wishes
